services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram_bot
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - .:/app
      - /app/node_modules

  redis:
    image: redis:7-alpine
    container_name: redis_container
    command: ["redis-server", "--requirepass", "qwert55"]
    env_file:
      - .env
